name: .NET CI Pipeline

on:
  push:
    branches: [ "feature/main" ]
  pull_request:
    branches: [ "feature/main" ]

jobs:
  build-test-analyze:
    name: Build, Test, Static Code Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore BookManagementAPI.sln
    
    - name: Clean solution
      run: dotnet clean BookManagementAPI.sln

    - name: Build solution
      run: dotnet build BookManagementAPI.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test BookManagementAPI.Test/BookManagementAPI.Test.csproj --no-build --configuration Release --verbosity normal --logger "console;verbosity=detailed"



