name: .NET

on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore BookManagementAPI.sln

    - name: Build
      run: dotnet build BookManagementAPI.sln --no-restore

    - name: Test
      run: dotnet test BookManagementAPI.sln --no-build --verbosity normal
