name: .NET Build and Test

on:
  push:
    branches: [ "feature/main" ]
  pull_request:
    branches: [ "feature/main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # Or whichever version you use

    - name: Restore dependencies
      run: dotnet restore BookManagementAPI.sln

    - name: Build
      run: dotnet build BookManagementAPI.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test BookManagementAPI.sln --no-build --verbosity normal
